### ISSUE TITLE
Error:No module pcsolver_v1p4

### ISSUE THREAD

**Issue by Player11132** [mycropht/PrimeCuber-for-Mindstorms-51515#1]
It does not find the desired file , what do I need to do ? Here are some screenshots
https://screenrec.com/share/Ku8U4L6Np0
https://screenrec.com/share/PSfRG2YBuO
https://screenrec.com/share/nEQNFdfKJS
I didnt change anything in the code .

**Comment by mycropht** [comment]
The PC Solver project should be started first and it will load the following files into the hub:

- pccolors_v1p4.py
- primecuber_v1p4.py
- pcmtab1_v1p4.bin

After the program has finished (it takes some time!), the PrimeCuber project has to be started as it is calling the programs loaded by PC Solver.

**Comment by 6and7-git** [comment]
where is the tab4 file? I cant find it.

**Comment by mycropht** [comment]
Tab4 is an optional part, as stated on the David Gilday's web (https://mindcuber.com/primecuber/primecuber.html#Software):

_Optional python projects, PCMTab4-v2p1-0.py to PCMTab4-v2p1-39.py, that together contain data for large lookup tables.

With the large lookup tables installed, PrimeCuber will solve the Rubik's Cube more quickly in an average of about 31 moves.

NOTE: These programs take a long time (between 30 and 60 minutes) to download and install on the SPIKE hub so it may be desirable to just use the small tables initially to get PrimeCuber working._

It is not included in this project.

**Comment by 6and7-git** [comment]
No on the mindstorms 51515 hub. I cant find the tab4 file

**Comment by mycropht** [comment]
It should be possible but I cannot confirm it.
